### PR TITLE
Update to use ver 6.03 of syslinux

### PR DESCRIPTION
**Pull request by pjfoley**
Update module to use the latest version of syslinux

### CODE REVIEW

**Comment by xaque208** [comment]
Nice!  Has this been tested?

**Comment by pjfoley** [comment]
I am using it on Debian Wheezy, it downloads the syslinux files and I have used it to pxe boot systems.

I have not tried the memdisk executable however everything else has been tested (vesa menu, text menu, reboot).  I can successfully boot into an installation image.

**Comment by pjfoley** [comment]
I am curious what your view is on adding another dependent module?  I think it makes sense to make use of the puppet-community/puppet-archive module.  

I was thinking of making the change to use the archive module however was not sure if you would accept that change?

**Comment by xaque208** [comment]
Awesome, thanks for the contribution.  @pjfoley I'm open to using an archive module to get rid of all the execs, etc.  This module predates many of those modules, but that doesn't mean we need to use old practice.

**Pull request merged**
